app:
  name: "App API"
  version: "1.0.0"

persistence:
  driver: sqlite
  sqlite:
    db_path: test.db
    echo: false

logging:
  level: INFO
  format: json
  outputs:
  - type: console
  - type: file
    path: logs/app.log
    max_bytes: 52428800
    backup_count: 5