app:
  name: "App API"
  version: "1.0.0"

logger:
    level: "DEBUG"
    format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
    date_format: "%Y-%m-%d %H:%M:%S"

postgres:
  username: "templateAdmin"
  password: !ENV ${POSTGRES_PASSWORD}
  host: "localhost"
  port: 5432
  dbname: "templatedb"
  echo: true  # SQLAlchemy echo logs
  pool_size: 10
  max_over_flow: 10
  pool_timeout: 30



retry:
  read_operations:
    max_tries: 3
    backoff_factor: 1.5
    exceptions: ["SQLAlchemyError", "OperationalError", "TimeoutError"]
  write_operations:
    max_tries: 5
    backoff_factor: 2.0
    exceptions: ["SQLAlchemyError", "OperationalError", "IntegrityError"]
  critical_operations:
    max_tries: 7
    backoff_factor: 2.5
    exceptions: ["Exception"]
