app:
  name: "App API"
  version: "1.0.0"

postgres:
  username: "templateAdmin"
  password: !ENV ${POSTGRES_PASSWORD}
  host: "localhost"
  port: 5432
  dbname: "templatedb"
  echo: true  # SQLAlchemy echo logs
  poolSize: 10
  maxOverFlow: 10
  poolTimeout: 30



retry:
  read_operations:
    max_tries: 3
    backoff_factor: 1.5
    exceptions: ["SQLAlchemyError", "OperationalError", "TimeoutError"]
  write_operations:
    max_tries: 5
    backoff_factor: 2.0
    exceptions: ["SQLAlchemyError", "OperationalError", "IntegrityError"]
  critical_operations:
    max_tries: 7
    backoff_factor: 2.5
    exceptions: ["Exception"]
