app:
  name: "Orthopedic Spine API"
  version: "1.0.0"

postgres:
  username: "templateAdmin"
  password: !ENV ${POSTGRES_PASSWORD}
  host: "localhost"
  port: 5432
  dbname: "templatedb"
  echo: true  # SQLAlchemy echo logs
  poolSize: 10
  maxOverFlow: 10
  poolTimeout: 30
